/**
 * SparkleIndicator.jsx
 * A small 8px 4-point star (sparkle) rendered in --graphite color.
 * Shows a CSS-only tooltip on hover: "Generated by Quest Lab AI — reviewed by your guide."
 */

const styles = {
  wrapper: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'default',
    flexShrink: 0,
  },
  tooltipText: {
    // Hidden by default; revealed on wrapper:hover via sibling selector workaround
    // using a class toggle approach via CSS injected once into the head.
  },
};

/*
 * We inject a small <style> block once so we can use pure CSS :hover on the
 * wrapper without needing any JS state.  This keeps the component dependency-free
 * while still satisfying the "CSS-only tooltip" requirement.
 */
let styleInjected = false;
function injectStyles() {
  if (styleInjected || typeof document === 'undefined') return;
  styleInjected = true;
  const el = document.createElement('style');
  el.textContent = `
    .ql-sparkle-wrapper {
      position: relative;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      cursor: default;
      flex-shrink: 0;
    }
    .ql-sparkle-tooltip {
      position: absolute;
      bottom: calc(100% + 6px);
      left: 50%;
      transform: translateX(-50%);
      background: var(--ink);
      color: var(--chalk);
      font-family: var(--font-body);
      font-size: 11px;
      line-height: 1.4;
      white-space: nowrap;
      padding: 4px 8px;
      border-radius: 4px;
      pointer-events: none;
      opacity: 0;
      transition: opacity 120ms ease;
      z-index: 100;
    }
    /* Arrow */
    .ql-sparkle-tooltip::after {
      content: '';
      position: absolute;
      top: 100%;
      left: 50%;
      transform: translateX(-50%);
      border: 4px solid transparent;
      border-top-color: var(--ink);
    }
    .ql-sparkle-wrapper:hover .ql-sparkle-tooltip {
      opacity: 1;
    }
  `;
  document.head.appendChild(el);
}

export default function SparkleIndicator() {
  injectStyles();

  /*
   * 4-point star (sparkle) path.
   * The star is drawn in an 8x8 viewBox using four diamond-style points:
   * top, right, bottom, left — with concave sides between each point.
   */
  return (
    <span className="ql-sparkle-wrapper" role="img" aria-label="AI-generated, guide-reviewed">
      <svg
        width="8"
        height="8"
        viewBox="0 0 8 8"
        fill="var(--graphite)"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        {/*
          4-point star path:
          Start at top point, curve inward to right quadrant, out to right point,
          curve inward to bottom quadrant, out to bottom point, etc.
          Uses quadratic bezier curves with the center (4,4) as the control point
          for each concave section.
        */}
        <path d="
          M4,0
          Q4.5,3.5 8,4
          Q4.5,4.5 4,8
          Q3.5,4.5 0,4
          Q3.5,3.5 4,0
          Z
        " />
      </svg>
      <span className="ql-sparkle-tooltip">
        Generated by Quest Lab AI — reviewed by your guide.
      </span>
    </span>
  );
}
